# Generated by Django 5.1.1 on 2024-09-07 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('invoice', models.CharField(max_length=20)),
                ('customer', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('product', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('awaiting', 'Awaiting'), ('unpaid', 'Unpaid')], default='unpaid', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_surname', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('receiver_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('reciver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_todos', to='main.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_todos', to='main.user')),
            ],
        ),
    ]
