# Generated by Django 5.1.1 on 2024-09-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_exhibition_user_groups_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_code',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
